modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/particle-spawner/issues"

[[mods]]
modId="particle_spawner"
version="1.1.2"
displayName="Particle Spawner"
itemIcon="minecraft:spawner"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/ParticleSpawner"
displayURL="https://www.curseforge.com/minecraft/mc-mods/particle-spawner"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
This mod adds a spawner that is invisible itself and spawns different particles with adjustable strength and range!
'''

[[dependencies.particle_spawner]]
    modId="forge"
    mandatory=true
    versionRange="[41,41.0.64)"
    ordering="NONE"
    side="BOTH"

[[dependencies.particle_spawner]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"