modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/particle-spawner/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="particle_spawner:particle_spawner"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/ParticleSpawner/refs/heads/main/versions.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/particle-spawner"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This mod adds a spawner that is invisible itself and spawns different particles with adjustable strength and range!'''

[modproperties.${mod_id}]
configuredBackground="minecraft:textures/block/spawner.png"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="magmacore"
referralUrl="https://www.curseforge.com/minecraft/mc-mods/magma-core"
reason="Provides basic code and features such as update-checker"
type="required"
versionRange="${magmacore_version_range}"
ordering="AFTER"
side="BOTH"